# Generated by Django 5.1.5 on 2025-02-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "매장_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("매장명", models.CharField(max_length=255)),
                ("매장_비밀번호", models.CharField(max_length=255)),
            ],
        ),
    ]
