# Generated by Django 5.1.5 on 2025-02-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="store",
            table="매장",
        ),
    ]
