# Generated by Django 5.1.5 on 2025-06-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="매장_아이디",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
