"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-n*xl2+suiylbhb+$x#_0mo%r&-vrk+=5g0&hr+hm!^2d2e2-dd"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ["192.168.0.11", "192.168.0.6", "localhost", "127.0.0.1"]
ALLOWED_HOSTS = ["*"]  # 모든 도메인 허용 (개발용)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "accounts",
    "analytics",
    "inventory",
    "orders",
    "sales",
    "suppliers",
    "management",
    "tasks",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # CORS 설정 추가
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True  # 모든 도메인 허용 (개발용)

# CORS_ALLOWED_ORIGINS = [
#     "http://192.168.0.6:3000",
#     "http://localhost:3000",  # React 웹 (개발 환경)
#     "http://localhost:19006",  # React Native 앱 (Expo 개발 환경)
#     "http://192.168.0.11:8081"
# ]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "khuffee",  # MySQL 데이터베이스 이름
        "USER": "root",  # MySQL 유저명
        "PASSWORD": "9420",  # MySQL 비밀번호
        "HOST": "localhost",  # 로컬 개발이면 'localhost'
        "PORT": "3306",  # 기본 MySQL 포트
        "OPTIONS": {"init_command": "SET sql_mode='STRICT_TRANS_TABLES'"},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery settings
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # 창고 발주 자동 생성 (매월 1일 0시)
    "create-monthly-warehouse-orders": {
        "task": "tasks.tasks.create_monthly_warehouse_orders",
        "schedule": crontab(day_of_month="1", hour=0, minute=0),
    },
    # 매장 재고 이월 (매일 0시)
    "store-inventory-rollover": {
        "task": "tasks.tasks.store_inventory_rollover",
        "schedule": crontab(hour=0, minute=0),
    },
    # 창고 재고 이월 (매일 0시)
    "warehouse-inventory-rollover": {
        "task": "tasks.tasks.warehouse_inventory_rollover",
        "schedule": crontab(hour=0, minute=0),
    },
    # 매장 발주 상태 리셋 (매주 월요일 0시; 시작일이 2025-03-03인 월요일)
    "reset-store-order-status": {
        "task": "tasks.tasks.reset_store_order_status",
        "schedule": crontab(day_of_week="mon", hour=0, minute=0),
    },
    # 창고 발주 상태 리셋 (매월 1일 0시)
    "reset-warehouse-order-status": {
        "task": "tasks.tasks.reset_warehouse_order_status",
        "schedule": crontab(day_of_month="1", hour=0, minute=0),
    },
    # 매장 월말재고 상태 리셋 (매월 1일 0시)
    "reset-store-month-end-inventory-status": {
        "task": "tasks.tasks.reset_store_month_end_inventory_status",
        "schedule": crontab(day_of_month="1", hour=0, minute=0),
    },
    # 창고 재고 상태 리셋 (매일 0시)
    "reset-warehouse-inventory-status": {
        "task": "tasks.tasks.reset_warehouse_inventory_status",
        "schedule": crontab(hour=0, minute=0),
    },
}
