# Generated by Django 5.1.5 on 2025-02-07 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("기간", models.CharField(max_length=10)),
                ("매장_발주량", models.IntegerField()),
                (
                    "매장_id",
                    models.ForeignKey(
                        db_column="매장_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.store",
                    ),
                ),
                (
                    "품목_id",
                    models.ForeignKey(
                        db_column="품목_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="suppliers.item",
                    ),
                ),
            ],
            options={
                "db_table": "매장_발주",
                "unique_together": {("매장_id", "품목_id", "기간")},
            },
        ),
        migrations.CreateModel(
            name="WarehouseIncoming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("기간", models.CharField(max_length=10)),
                ("창고_입고량", models.IntegerField()),
                (
                    "매장_id",
                    models.ForeignKey(
                        db_column="매장_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.store",
                    ),
                ),
                (
                    "품목_id",
                    models.ForeignKey(
                        db_column="품목_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="suppliers.item",
                    ),
                ),
            ],
            options={
                "db_table": "창고_입고",
                "unique_together": {("매장_id", "품목_id", "기간")},
            },
        ),
        migrations.CreateModel(
            name="WarehouseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("기간", models.CharField(max_length=10)),
                ("창고_발주량", models.IntegerField()),
                (
                    "품목_id",
                    models.ForeignKey(
                        db_column="품목_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="suppliers.item",
                    ),
                ),
                (
                    "협력사_id",
                    models.ForeignKey(
                        db_column="협력사_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "창고_발주",
                "unique_together": {("협력사_id", "품목_id", "기간")},
            },
        ),
        migrations.CreateModel(
            name="WarehouseOutgoing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("기간", models.CharField(max_length=10)),
                ("창고_출고량", models.IntegerField()),
                (
                    "매장_id",
                    models.ForeignKey(
                        db_column="매장_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.store",
                    ),
                ),
                (
                    "품목_id",
                    models.ForeignKey(
                        db_column="품목_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="suppliers.item",
                    ),
                ),
            ],
            options={
                "db_table": "창고_출고",
                "unique_together": {("매장_id", "품목_id", "기간")},
            },
        ),
    ]
