# Generated by Django 5.1.5 on 2025-01-30 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "store_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("store_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="orders.store",
                    ),
                ),
                ("store_name", models.CharField(max_length=255)),
                ("store_pw", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
