# Generated by Django 5.1.5 on 2025-02-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("orders", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="storeorder",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="storeorder",
            name="회차",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="storeorder",
            unique_together={("매장_id", "품목_id", "기간", "회차")},
        ),
    ]
