# Generated by Django 5.1.5 on 2025-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_storeorder_unique_together_storeorder_회차_and_more"),
        ("suppliers", "0002_alter_item_입고단가"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="warehouseorder",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="warehouseorder",
            name="회차",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="warehouseorder",
            name="기간",
            field=models.CharField(max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name="warehouseorder",
            unique_together={("협력사_id", "품목_id", "기간", "회차")},
        ),
    ]
