# Generated by Django 5.1.5 on 2025-03-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_warehouseorder_unique_together_and_more"),
        ("suppliers", "0002_alter_item_입고단가"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="warehouseorder",
            unique_together={("품목_id", "기간", "회차")},
        ),
        migrations.RemoveField(
            model_name="warehouseorder",
            name="협력사_id",
        ),
    ]
