# Generated by Django 5.1.5 on 2025-02-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TableStatus",
            fields=[
                (
                    "테이블",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("상태", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "상태_관리",
            },
        ),
    ]
