import { StyleSheet, Dimensions, TextStyle } from "react-native";
import { moderateScale, scale, verticalScale } from "react-native-size-matters";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { RFValue } from "react-native-responsive-fontsize";

const { height: screenHeight } = Dimensions.get("window");

// 색상 테마 정의 - StockManagement와 통일
const COLORS = {
  primary: "#0D326F", // 메인 컬러
  primaryLight: "#3B82F6",
  secondary: "#F97316",
  background: "#FFFFFF",
  card: "#FFFFFF",
  border: "#e2e8f0",
  text: {
    primary: "#1e293b",
    secondary: "#64748b",
    white: "#FFFFFF",
  },
  expiration: {
    normal: "#FFFFFF",
    warning: "#FEF9C3", // 30일 이내 (연한 노랑)
    nearExpiration: "#FFEDD5", // 7일 이내 (연한 주황)
    expired: "#FEE2E2", // 만료 (연한 빨강)
  },
  success: "#10b981", // 성공 메시지 색상
  error: "#ef4444", // 오류 메시지 색상
};

const commonTextStyle = (customStyle: Partial<TextStyle> = {}): TextStyle => ({
  fontFamily: "PretendardVariable",
  fontWeight: customStyle.fontWeight ? customStyle.fontWeight : "400",
  ...customStyle,
});

export const styles = StyleSheet.create({
  container: {
    ...commonTextStyle,
    flex: 1,
    alignItems: "stretch",
    justifyContent: "flex-start",
    backgroundColor: "#fff",
    marginHorizontal: moderateScale(10),
    paddingBottom: moderateScale(0), //추후 높이 맞출 때 쓰기
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  title: {
    ...commonTextStyle({ fontWeight: "700" }),
    fontSize: RFValue(18),
    marginBottom: moderateScale(12),
    color: COLORS.primary,
    width: "65%",
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary,
    paddingLeft: moderateScale(5),
    marginLeft: moderateScale(5),
  },
  filterContainer: {
    marginBottom: moderateScale(0),
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.card,
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: moderateScale(12),
    marginTop: moderateScale(5),
    marginBottom: moderateScale(5),
    // height: 45,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    overflow: "hidden",
  },
  searchInput: {
    flex: 1,
    height: 40,
    marginLeft: 8,
    fontSize: RFValue(14),
    color: COLORS.text.primary,
    ...commonTextStyle(),
  },
  clearButton: {
    padding: 6,
  },
  sortButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  // StockManagement와 동일한 버튼 스타일
  sortButton: {
    backgroundColor: "#f8fafc",
    paddingHorizontal: moderateScale(10),
    paddingVertical: verticalScale(5),
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 2,
    justifyContent: "center",
    alignItems: "center",
  },
  sortButtonText: {
    ...commonTextStyle({ fontWeight: "500" }),
    color: COLORS.primary,
    fontSize: RFValue(11),
  },
  activeSort: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: moderateScale(10),
    paddingVertical: verticalScale(5),
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: COLORS.primary,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
    justifyContent: "center",
    alignItems: "center",
  },
  activeSortText: {
    color: COLORS.text.white,
    fontSize: RFValue(11),
    fontWeight: "600",
  },
  headerText: {
    ...commonTextStyle({ fontWeight: "600" }),
    fontSize: RFValue(13),
    color: COLORS.text.white,
    textAlign: "center",
    flex: 1,
  },
  cellText: {
    ...commonTextStyle(),
    fontSize: RFValue(12),
    color: COLORS.text.primary,
    textAlign: "center",
    flex: 1,
  },
  loadingText: {
    ...commonTextStyle,
    marginTop: moderateScale(3),
    fontSize: RFValue(16),
    fontWeight: "600",
    left: 5,
    color: "#00000080",
    alignItems: "center",
  },
  emptyText: {
    ...commonTextStyle(),
    textAlign: "center",
    marginTop: 20,
    fontSize: RFValue(15),
    color: COLORS.text.secondary,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: COLORS.primary,
    paddingVertical: moderateScale(8),
    borderTopLeftRadius: moderateScale(12),
    borderTopRightRadius: moderateScale(12),
    marginBottom: 0,
    minHeight: moderateScale(40),
  },
  tableContainer: {
    borderRadius: moderateScale(12),
    overflow: "hidden",
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
    marginBottom: moderateScale(5),
    backgroundColor: COLORS.card,
    flex: 1,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: moderateScale(4),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    minHeight: moderateScale(40),
    alignItems: "center",
  },
  evenRow: {
    backgroundColor: COLORS.card,
  },
  oddRow: {
    backgroundColor: "#f8fafc",
  },
  productCell: {
    flex: 4.3,
    // flexDirection: "column",
    // justifyContent: "center",
    // alignItems: "center",
    // paddingVertical: moderateScale(4),
  },
  productName: {
    fontSize: RFValue(12),
    color: COLORS.text.primary,
    textAlign: "center",
    marginBottom: 2,
  },
  supplierName: {
    fontSize: RFValue(10),
    color: COLORS.text.secondary,
    textAlign: "center",
  },
  dateCell: {
    flex: 2.8,
    marginLeft: moderateScale(10),
  },
  dateContainer: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  dateText: {
    fontSize: RFValue(12),
    color: COLORS.text.primary,
    textAlign: "center",
  },
  daysRemainingText: {
    fontSize: RFValue(10),
    color: COLORS.text.secondary,
    textAlign: "center",
    marginTop: 2,
  },
  quantityCell: {
    flex: 2,
  },
  stockCell: {
    flex: 1.3,
  },
  actionCell: {
    flex: 1,
    paddingHorizontal: 4,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  actionButton: {
    padding: moderateScale(5),
    backgroundColor: "#f8fafc",
    borderRadius: moderateScale(6),
    borderWidth: 1,
    borderColor: "#e2e8f0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 1,
  },
  legendContainer: {
    ...commonTextStyle(),
    flexDirection: "row",
    justifyContent: "space-around",
    flexWrap: "wrap",
    marginBottom: moderateScale(2),
    backgroundColor: COLORS.card,
    padding: moderateScale(2),
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 2,
    paddingHorizontal: 4,
  },
  legendColor: {
    width: 16,
    height: 16,
    borderRadius: 4,
    marginRight: 6,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  legendText: {
    ...commonTextStyle(),
    fontSize: RFValue(12),
    color: COLORS.text.secondary,
  },
  normal: {
    backgroundColor: COLORS.expiration.normal,
  },
  warning: {
    backgroundColor: COLORS.expiration.warning,
  },
  nearExpiration: {
    backgroundColor: COLORS.expiration.nearExpiration,
  },
  expired: {
    backgroundColor: COLORS.expiration.expired,
  },
  flatListStyle: {
    borderRadius: 12,
    overflow: "hidden",
    flex: 1,
  },

  // 모달 및 폼 관련 스타일
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: wp("85%"),
    backgroundColor: "#fff",
    borderRadius: moderateScale(16),
    paddingBottom: moderateScale(20),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    maxHeight: "90%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(12),
  },
  modalTitle: {
    ...commonTextStyle({ fontWeight: "700" }),
    fontSize: RFValue(18),
    color: COLORS.primary,
  },
  closeButton: {
    padding: moderateScale(5),
  },
  formContainer: {
    paddingHorizontal: moderateScale(16),
    paddingTop: moderateScale(10),
  },
  formGroup: {
    marginBottom: moderateScale(16),
  },
  label: {
    ...commonTextStyle({ fontWeight: "600" }),
    fontSize: RFValue(14),
    color: COLORS.text.primary,
    marginBottom: moderateScale(6),
  },
  input: {
    ...commonTextStyle(),
    height: moderateScale(46),
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: moderateScale(8),
    paddingHorizontal: moderateScale(12),
    fontSize: RFValue(14),
    color: COLORS.text.primary,
    backgroundColor: "#f8fafc",
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: moderateScale(8),
    backgroundColor: "#f8fafc",
    maxHeight: moderateScale(150),
  },
  pickerScrollView: {
    paddingVertical: moderateScale(5),
  },
  productItem: {
    paddingHorizontal: moderateScale(12),
    paddingVertical: moderateScale(10),
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  selectedProductItem: {
    backgroundColor: "#e0f2fe",
  },
  productItemText: {
    ...commonTextStyle(),
    fontSize: RFValue(14),
    color: COLORS.text.primary,
  },
  selectedProductText: {
    ...commonTextStyle({ fontWeight: "600" }),
    fontSize: RFValue(14),
    color: COLORS.primary,
  },
  dateInput: {
    ...commonTextStyle(),
    height: moderateScale(46),
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: moderateScale(8),
    paddingHorizontal: moderateScale(12),
    justifyContent: "center",
    backgroundColor: "#f8fafc",
  },
  disabledInput: {
    ...commonTextStyle(),
    height: moderateScale(46),
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: moderateScale(8),
    paddingHorizontal: moderateScale(12),
    justifyContent: "center",
    backgroundColor: "#f1f5f9",
  },
  disabledText: {
    ...commonTextStyle(),
    fontSize: RFValue(14),
    color: COLORS.text.secondary,
  },
  buttonGroup: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: moderateScale(20),
  },
  cancelButton: {
    backgroundColor: "#f1f5f9",
    paddingVertical: moderateScale(12),
    paddingHorizontal: moderateScale(25),
    borderRadius: moderateScale(10),
    borderWidth: 1,
    borderColor: "#e2e8f0",
    marginHorizontal: moderateScale(5),
    minWidth: wp("35%"),
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  cancelButtonText: {
    ...commonTextStyle({ fontWeight: "600" }),
    fontSize: RFValue(15),
    color: "#334155",
  },
  submitButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: moderateScale(12),
    paddingHorizontal: moderateScale(25),
    borderRadius: moderateScale(10),
    marginHorizontal: moderateScale(5),
    minWidth: wp("35%"),
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  submitButtonText: {
    ...commonTextStyle({ fontWeight: "600" }),
    fontSize: RFValue(15),
    color: "#ffffff",
  },

  // 성공 메시지 스타일
  successMessageContainer: {
    backgroundColor: "#d1fae5",
    padding: moderateScale(10),
    marginBottom: moderateScale(15),
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: "#a7f3d0",
  },
  successMessageText: {
    ...commonTextStyle(),
    color: "#065f46",
    fontSize: RFValue(14),
    textAlign: "center",
  },

  // 하단 버튼 스타일
  bottomButtonContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: moderateScale(8),
    backgroundColor: "#fff",
  },
  addButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: moderateScale(8),
    paddingHorizontal: moderateScale(20),
    borderRadius: moderateScale(8),
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
    flex: 1,
    marginRight: moderateScale(8),
  },
  addButtonText: {
    ...commonTextStyle({ fontWeight: "600" }),
    fontSize: RFValue(15),
    color: "#ffffff",
    marginLeft: moderateScale(8),
  },
  editButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: moderateScale(8),
    paddingHorizontal: moderateScale(20),
    borderRadius: moderateScale(8),
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
    flex: 1,
  },
  editButtonText: {
    ...commonTextStyle({ fontWeight: "600" }),
    fontSize: RFValue(15),
    color: "#ffffff",
    marginLeft: moderateScale(8),
  },
  saveButton: {
    backgroundColor: COLORS.success,
    paddingVertical: moderateScale(8),
    paddingHorizontal: moderateScale(20),
    borderRadius: moderateScale(8),
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  saveButtonText: {
    ...commonTextStyle({ fontWeight: "600" }),
    fontSize: RFValue(15),
    color: "#ffffff",
    marginLeft: moderateScale(8),
  },

  // 저장 완료 모달 스타일
  saveSuccessModal: {
    backgroundColor: "#ffffff",
    padding: moderateScale(20),
    borderRadius: moderateScale(12),
    alignItems: "center",
    width: wp("80%"),
  },
  saveSuccessText: {
    ...commonTextStyle({ fontWeight: "600" }),
    fontSize: RFValue(16),
    color: COLORS.success,
    marginBottom: moderateScale(10),
    textAlign: "center",
  },
  saveSuccessButton: {
    backgroundColor: COLORS.success,
    paddingVertical: moderateScale(8),
    paddingHorizontal: moderateScale(20),
    borderRadius: moderateScale(8),
  },
  saveSuccessButtonText: {
    ...commonTextStyle({ fontWeight: "600" }),
    fontSize: RFValue(14),
    color: "#ffffff",
  },

  // 협력사별 구분을 위한 스타일
  supplierHeader: {
    backgroundColor: "#f1f5f9",
    paddingVertical: moderateScale(8),
    paddingHorizontal: moderateScale(12),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  supplierHeaderText: {
    ...commonTextStyle({ fontWeight: "600" }),
    fontSize: RFValue(14),
    color: COLORS.primary,
  },
  supplierContent: {
    backgroundColor: COLORS.card,
  },
});

// StockManagement에서 직접 가져온 headerRowStyles 정의
export const headerRowStyles = StyleSheet.create({
  container: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginVertical: moderateScale(4),
  },
  rightContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  buttonContainer: {
    flexDirection: "row",
    gap: moderateScale(8),
  },
  smallButton: {
    backgroundColor: "#f8fafc",
    paddingHorizontal: moderateScale(10),
    paddingVertical: verticalScale(5),
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: "#0D326F",
    shadowColor: "#0D326F",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 2,
    justifyContent: "center",
    alignItems: "center",
    minWidth: moderateScale(80),
  },
  activeButton: {
    backgroundColor: "#0D326F",
    paddingHorizontal: moderateScale(10),
    paddingVertical: verticalScale(5),
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: "#0D326F",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
    justifyContent: "center",
    alignItems: "center",
    minWidth: moderateScale(80),
  },
  cancelButton: {
    backgroundColor: "#f8fafc",
    paddingHorizontal: moderateScale(10),
    paddingVertical: verticalScale(5),
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: "#e53e3e",
    shadowColor: "#e53e3e",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 2,
    justifyContent: "center",
    alignItems: "center",
    marginRight: moderateScale(5),
  },
  buttonText: {
    color: "#0D326F",
    fontSize: RFValue(11),
    fontWeight: "500",
  },
  activeButtonText: {
    color: "#FFFFFF",
    fontSize: RFValue(11),
    fontWeight: "600",
  },
  cancelButtonText: {
    color: "#e53e3e",
    fontSize: RFValue(11),
    fontWeight: "500",
  },
});
