import { StyleSheet, Dimensions,TextStyle } from 'react-native';
import { moderateScale, scale, verticalScale } from 'react-native-size-matters';
import { RFValue } from 'react-native-responsive-fontsize';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

const { height: screenHeight } = Dimensions.get('window');

const commonTextStyle = (customStyle: Partial<TextStyle> = {}): TextStyle => ({
  fontFamily: 'PretendardVariable',
  fontWeight: customStyle.fontWeight ? customStyle.fontWeight : '400',
  ...customStyle,
});


export const inventoryStyles = StyleSheet.create({
    container: {
      ...commonTextStyle,
      flex: 1,
      padding: moderateScale(20),
      backgroundColor: '#fff',
    },
      term_of_name: {
        ...commonTextStyle,
        fontSize: RFValue(16),
        fontWeight: 'bold',
        marginBottom: moderateScale(10),
        color: '#0D326F',
      },
    title: {
      ...commonTextStyle,
      fontSize: RFValue(18),
      fontWeight: '700',
      color: '#0D326F',
      marginBottom: moderateScale(12),
      // paddingHorizontal: moderateScale(16),
      width: '65%',
      borderLeftWidth: 4,
      borderLeftColor: '#0D326F',
      paddingLeft: moderateScale(5),
      marginLeft: moderateScale(5)
    },
    inventory_HeaderContainer: {
      ...commonTextStyle,
      backgroundColor: '#f8f9fa',
      borderWidth: 1,
      borderColor: '#e2e8f0',
      // borderRadius: moderateScale(12),
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: moderateScale(16),
      paddingVertical: moderateScale(12),
      // marginBottom: moderateScale(10),
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    inventory_item_headerText: {
      ...commonTextStyle,
      width: '65%',
      fontSize: RFValue(15),
      fontWeight: '700',
      color: '#0A2A5E',
      textAlign: 'left',
    },
    inventory_unit_headerText: {
      ...commonTextStyle,
      width: '35%',
      fontSize: RFValue(15),
      fontWeight: '700',
      color: '#0A2A5E',
      textAlign: 'center',
      marginLeft: moderateScale(15),
    },
    itemContainer: {
      ...commonTextStyle,
      backgroundColor: '#fff',
      borderWidth: 1,
      borderColor: '#e2e8f0',
      // borderRadius: moderateScale(10),
      // marginBottom: moderateScale(8),
      padding: moderateScale(15),
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 3,
      elevation: 2,
    },
    name_itemText: {
      ...commonTextStyle,
      width: '65%',
      fontSize: RFValue(15),
      fontWeight: '500',
      color: '#1e293b',
      letterSpacing: -0.3,
    },
    unit_itemText: {
      ...commonTextStyle,
      width: '20%',
      fontSize: RFValue(15),
      fontWeight: '600',
      color: '#0A2A5E',
      textAlign: 'center',
      borderWidth: 1,
      borderColor: '#e2e8f0',
      borderRadius: moderateScale(8),
      paddingVertical: moderateScale(4),
      paddingHorizontal: moderateScale(6),
      backgroundColor: '#f8fafc',
    },
    inventory_selectItemRowContainer: {
      ...commonTextStyle,
      flexDirection: 'row',
      alignItems: 'center',
      paddingRight: moderateScale(6),
      paddingLeft: moderateScale(2),
      gap: moderateScale(30),
      position: 'relative',
    },
    flat_inventory: {
      ...commonTextStyle,
      flex: 1,
      marginBottom: moderateScale(10),
    },
    editButton: {
      ...commonTextStyle,
      backgroundColor: '#0D326F',
      borderRadius: 25,
      paddingVertical: moderateScale(12),
      paddingHorizontal: moderateScale(30),
      marginTop: moderateScale(10),
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 3,
    },
    editButtonText: {
      ...commonTextStyle,
      color: '#ffffff',
      fontSize: RFValue(16),
      fontWeight: 'bold',
      textAlign: 'center',
    },
    message: {
      ...commonTextStyle,
      fontSize: RFValue(16),
      color: '#555',
      textAlign: 'center',
      marginTop: 20,
    },
    status_container: {
      ...commonTextStyle,
      flex: 1,
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      backgroundColor: '#fff',
      paddingHorizontal: moderateScale(16),
    },
    inventory_cardContent: {
      ...commonTextStyle,
      flexDirection: 'column',
      width: '100%',
      // height: hp(3)
    },
  });
  export const toggleButtonStyles = StyleSheet.create({
    container: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: moderateScale(10),
      gap: moderateScale(1),
    },
    headerContainer: {
      backgroundColor: '#f8fafc',
      borderRadius: moderateScale(10),
      padding: moderateScale(8),
      marginHorizontal: moderateScale(10),
      marginBottom: moderateScale(10),
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    button: {
      flex: 1,
      paddingVertical: moderateScale(8),
      paddingHorizontal: moderateScale(16),
      borderRadius: moderateScale(6),
      borderWidth: 1,
      borderBottomWidth: 0.3,
      borderColor: '#e0e0e0',
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
      borderBottomRightRadius: 0,
      borderBottomLeftRadius: 0,
    },
    buttonActive: {
      backgroundColor: '#0A2A5E',
      borderWidth: 0,
      borderColor: 'transparent',
      borderBottomRightRadius: 0,
      borderBottomLeftRadius: 0,
    },
    buttonText: {
      fontSize: 14,
      color: '#0A2A5E',
      fontWeight: 'bold',
    },
    buttonTextActive: {
      color: '#fff',
    },
  });
  
  export const headerRowStyles = StyleSheet.create({
    container: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      marginVertical: moderateScale(4),
    },
    rightContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    buttonContainer: {
      flexDirection: 'row',
      gap: moderateScale(10),
    },
    smallButton: {
      backgroundColor: '#f8fafc',
      paddingHorizontal: moderateScale(10),
      paddingVertical: verticalScale(5),
      borderRadius: moderateScale(8),
      borderWidth: 1,
      borderColor: '#0D326F',
      shadowColor: '#0D326F',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 1.5,
      elevation: 2,
      justifyContent: 'center',
      alignItems: 'center',
    },
    activeButton: {
      backgroundColor: '#0D326F',
      paddingHorizontal: moderateScale(10),
      paddingVertical: verticalScale(5),
      borderRadius: moderateScale(8),
      borderWidth: 1,
      borderColor: '#0D326F',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 3,
      justifyContent: 'center',
      alignItems: 'center',
    },
    buttonText: {
      ...commonTextStyle,
      color: '#0D326F',
      fontSize: RFValue(11),
      fontWeight: '500',
    },
    activeButtonText: {
      ...commonTextStyle,
      color: '#FFFFFF',
      fontSize: RFValue(11),
      fontWeight: '600',
    },
    disabledButton: {
      backgroundColor: '#0D326F',
      paddingHorizontal: moderateScale(10),
      paddingVertical: verticalScale(5),
      borderRadius: moderateScale(8),
      borderWidth: 1,
      borderColor: '#cccccc',
      shadowColor: '#999999',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 1,
      elevation: 1,
      justifyContent: 'center',
      alignItems: 'center',
      opacity: 0.7,
    },
    disabledButtonText: {
      ...commonTextStyle,
      color: '#ffffff',
      fontSize: RFValue(11),
      fontWeight: '400',
    },
  });
  
  export const modalStyles = StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContainer: {
      width: '80%',
      backgroundColor: '#fff',
      padding: moderateScale(20),
      borderRadius: moderateScale(10),
      alignItems: 'center',
    },
    modalText: {
      marginBottom: moderateScale(20),
      fontSize: 16,
      textAlign: 'center',
    },
  });
  
  export const searchStyles = StyleSheet.create({
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: moderateScale(5),
      borderWidth: 1,
      borderColor: '#e2e8f0',
      borderRadius: moderateScale(8),
      backgroundColor: '#fff',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
      overflow: 'hidden',
    },
    searchInput: {
      flex: 1,
      paddingVertical: moderateScale(10),
      paddingHorizontal: moderateScale(12),
      fontSize: 14,
      color: '#1e293b',
    },
    searchIcon: {
      padding: moderateScale(10),
    },
    searchIconSize: {
      width: 20,
      height: 20,
    },
    searchIconContainer: {
      marginRight: moderateScale(8),
      borderRadius: moderateScale(20),
    },
  });
  
  export const editModeStyles = StyleSheet.create({
    controlContainer: {
      width: '20%',
      position: 'relative',
    },
    controlButtonsGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
      position: 'relative',
    },
    controlButtonsContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      position: 'absolute',
      right: 0,
    },
    controlButton: {
      padding: moderateScale(4),
      borderWidth: 1,
      borderColor: '#e2e8f0',
      borderRadius: moderateScale(6),
      backgroundColor: '#f8fafc',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 1,
      elevation: 1,
      width: moderateScale(26),
      height: moderateScale(26),
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      zIndex: 1,
    },
    deleteButton: {
      padding: moderateScale(6),
      borderWidth: 1,
      borderColor: '#ffcccc',
      borderRadius: moderateScale(8),
      marginLeft: moderateScale(4),
      backgroundColor: '#fff5f5',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 1,
      elevation: 1,
    },
    quantityInput: {
      width: '100%',
      textAlign: 'center',
      borderWidth: 1,
      borderColor: '#e2e8f0',
      borderRadius: moderateScale(8),
      paddingVertical: moderateScale(4),
      paddingHorizontal: moderateScale(6),
      // backgroundColor: '#f8fafc',
      fontSize: RFValue(15),
      fontWeight: '600',
      // color: '#0A2A5E',
    },
    leftButton: {
      position: 'absolute',
      left: moderateScale(-30),
      top: moderateScale(7),
      transform: [{ translateY: -13 }],
    },
    rightButton: {
      position: 'absolute',
      right: moderateScale(-30),
      top: moderateScale(7),
      transform: [{ translateY: -13 }],
    },
  });