import { StyleSheet, Dimensions } from 'react-native';
import { moderateScale, scale, verticalScale } from 'react-native-size-matters';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';
import { RFValue } from 'react-native-responsive-fontsize';

const { height: screenHeight } = Dimensions.get('window');

const commonTextStyle = {
  fontFamily: 'Pretendard-Regular',
};

export const orderStatusStyles = StyleSheet.create({
  /* ========== 로딩 관련 ========== */
  loading_Container: {
    ...commonTextStyle,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  loading_Text: {
    ...commonTextStyle,
    marginTop: moderateScale(3),
    fontSize: RFValue(16),
    fontWeight: '600',
    left: 5,
    color: '#00000080',
    alignItems: 'center',
  },

  /* ========== 헤더 영역 ========== */
  headerRow: {
    ...commonTextStyle,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingTop: moderateScale(5),
    paddingRight: moderateScale(-5),
    paddingBottom: moderateScale(-8),
  },
  sectionTitle: {
    ...commonTextStyle,
    fontSize: RFValue(18),
    fontWeight: '700',
    color: '#0D326F',
    marginBottom: moderateScale(12),
    paddingHorizontal: moderateScale(16),
    width: '100%',
    borderLeftWidth: 4,
    borderLeftColor: '#0D326F',
    paddingLeft: moderateScale(10),
    marginLeft: moderateScale(5),
  },
  title: {
    ...commonTextStyle,
    fontSize: RFValue(16),
    fontWeight: 'bold',
    marginBottom: 10,
    paddingHorizontal: moderateScale(16),
  },
  rightButtonGroup: {
    ...commonTextStyle,
    flexDirection: 'row',
    alignItems: 'center',
  },
  sortButton: {
    ...commonTextStyle,
    justifyContent: 'center',
    alignItems: 'center',
    width: 79,
    height: 40,
    backgroundColor: 'white',
    borderColor: '#0D326F',
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
  },

  /* ========== 목록 및 버튼 ========== */
  term_of_name: {
    ...commonTextStyle,
    fontSize: RFValue(16),
    fontWeight: 'bold',
    marginBottom: moderateScale(10),
    color: '#0D326F',
  },
  loadMoreButton: {
    ...commonTextStyle,
    alignSelf: 'center',
    marginVertical: moderateScale(10),
    backgroundColor: '#0D326F',
    borderRadius: 8,
    paddingVertical: moderateScale(10),
    paddingHorizontal: moderateScale(20),
  },
  loadMoreButtonText: {
    ...commonTextStyle,
    color: '#fff',
    fontSize: RFValue(16),
    fontWeight: 'bold',
  },

  /* ========== FlatList 스타일 (orderStatusStyles) ========== */
  flatlist: {
    ...commonTextStyle,
    height: hp(80),
  },
  dateHeader: {
    ...commonTextStyle,
    fontSize: RFValue(18),
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#333',
    paddingLeft: 4,
  },
  extraCountText: {
    ...commonTextStyle,
    color: '#0D326F',
    fontWeight: 'bold',
    marginBottom: 4,
  },
  productName: {
    ...commonTextStyle,
    fontSize: RFValue(16),
    fontWeight: '600',
    marginBottom: 4,
  },
  quantity: {
    ...commonTextStyle,
    fontSize: RFValue(14),
    color: '#555',
    marginBottom: 6,
  },
  actionButton: {
    ...commonTextStyle,
    backgroundColor: 'white',
    borderColor: '#0D326F',
    borderWidth: 2,
    borderRadius: 6,
    width: wp(20),
    height: hp(5),
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionButtonText: {
    ...commonTextStyle,
    color: '#0D326F',
    fontSize: RFValue(14),
    fontWeight: 'bold',
    textAlign: 'center',
  },

  /* ========== 모달 관련 (modalStyles) ========== */
  centeredView: {
    ...commonTextStyle,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalView: {
    ...commonTextStyle,
    margin: moderateScale(20),
    backgroundColor: '#ffffff',
    borderRadius: moderateScale(12),
    padding: moderateScale(25),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '85%',
  },
  closeButton: {
    ...commonTextStyle,
    backgroundColor: '#0D326F',
    borderRadius: moderateScale(25),
    paddingVertical: moderateScale(12),
    paddingHorizontal: moderateScale(30),
    elevation: 2,
    marginTop: moderateScale(20),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  textStyle: {
    ...commonTextStyle,
    color: '#ffffff',
    fontWeight: '700',
    fontSize: RFValue(16),
    textAlign: 'center',
  },

  /* ========== 영수증 관련 (receiptStyles) ========== */
  receiptContainer: {
    ...commonTextStyle,
    width: '100%',
    padding: 20,
    backgroundColor: '#fff',
  },
  header: {
    ...commonTextStyle,
    alignItems: 'center',
    marginBottom: 10,
  },
  headerTitle: {
    ...commonTextStyle,
    fontSize: RFValue(20),
    fontWeight: 'bold',
  },
  headerSubtitle: {
    ...commonTextStyle,
    fontSize: RFValue(14),
    color: '#666',
    marginTop: 2,
  },
  divider: {
    ...commonTextStyle,
    borderBottomColor: '#ccc',
    borderBottomWidth: 1,
    borderStyle: 'dashed',
    marginVertical: 8,
  },
  itemRow: {
    ...commonTextStyle,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  itemRowLeft: {
    ...commonTextStyle,
    flexDirection: 'column',
  },
  itemRowRight: {
    ...commonTextStyle,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  itemName: {
    ...commonTextStyle,
    fontSize: RFValue(16),
    fontWeight: '600',
  },
  itemQty: {
    ...commonTextStyle,
    fontSize: RFValue(14),
    color: '#666',
    marginTop: 2,
  },
  itemPrice: {
    ...commonTextStyle,
    fontSize: RFValue(16),
    fontWeight: '600',
    color: '#0D326F',
  },
  footer: {
    ...commonTextStyle,
    marginTop: 10,
    alignItems: 'flex-end',
  },
  footerText: {
    ...commonTextStyle,
    color: '#1e7e34',
    fontSize: RFValue(16),
    fontWeight: 'bold',
  },

  /* ========== 기간조회 및 날짜 선택 모달 (styles) ========== */
  periodModalContainer: {
    ...commonTextStyle,
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  periodModalInner: {
    ...commonTextStyle,
    width: '80%',
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 20,
    overflow: 'visible',
  },
  periodModalTitle: {
    ...commonTextStyle,
    fontSize: RFValue(18),
    fontWeight: 'bold',
    marginBottom: 16,
  },
  dateGroup: {
    ...commonTextStyle,
    flex: 1,
    alignItems: 'center',
    marginTop: 12,
  },
  dateGroupLabel: {
    ...commonTextStyle,
    fontSize: RFValue(16),
    fontWeight: 'bold',
    marginBottom: 6,
  },
  dateRow: {
    ...commonTextStyle,
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
  },
  dateBox: {
    ...commonTextStyle,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 5,
    width: 75,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateBoxText: {
    ...commonTextStyle,
    fontSize: RFValue(15),
    fontWeight: '600',
  },
  dropdownWrapper: {
    ...commonTextStyle,
    position: 'relative',
    marginHorizontal: 4,
    zIndex: 1,
  },
  dropdown: {
    ...commonTextStyle,
    position: 'absolute',
    top: '100%',
    left: 0,
    width: '100%',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 6,
    zIndex: 10,
    elevation: 10,
  },
  dropdownOpen: {
    ...commonTextStyle,
    zIndex: 9999,
    elevation: 9999,
  },
  dropdownItem: {
    ...commonTextStyle,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  dropdownScroll: {
    ...commonTextStyle,
    maxHeight: 180,
  },
  confirmButton: {
    ...commonTextStyle,
    backgroundColor: '#3b82f6',
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginTop: 10,
  },
  confirmButtonText: {
    ...commonTextStyle,
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  periodSearchButton: {
    ...commonTextStyle,
    backgroundColor: '#0D326F',
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  periodSearchButtonText: {
    ...commonTextStyle,
    color: '#fff',
    fontWeight: 'bold',
  },
  resetButton: {
    ...commonTextStyle,
    backgroundColor: 'red',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
  },
  resetButtonText: {
    ...commonTextStyle,
    color: '#fff',
    fontWeight: 'bold',
  },
  datePickerModalContainer: {
    ...commonTextStyle,
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  datePickerModal: {
    ...commonTextStyle,
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 20,
    alignItems: 'center',
  },
  datePickerTitle: {
    ...commonTextStyle,
    fontSize: RFValue(18),
    fontWeight: 'bold',
    marginBottom: 10,
  },
  datePickerLabel: {
    ...commonTextStyle,
    fontSize: RFValue(14),
    fontWeight: '600',
    marginVertical: 6,
    alignSelf: 'flex-start',
  },
  pickerItem: {
    ...commonTextStyle,
    backgroundColor: '#eee',
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginRight: 6,
  },
  pickerItemActive: {
    ...commonTextStyle,
    backgroundColor: '#3b82f6',
  },
    status_flatlist: {
      ...commonTextStyle,
      height: hp(80),
    },
  });
