import { StyleSheet, Dimensions,TextStyle  } from 'react-native';
import { moderateScale, scale, verticalScale } from 'react-native-size-matters';
import { RFValue } from 'react-native-responsive-fontsize';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

const { height: screenHeight } = Dimensions.get('window');

const commonTextStyle = (customStyle: Partial<TextStyle> = {}): TextStyle => ({
  fontFamily: 'PretendardVariable',
  fontWeight: customStyle.fontWeight ? customStyle.fontWeight : '400',
  ...customStyle,
});

export const OrderRequeststyle = StyleSheet.create({
  selectItemCard: {
    ...commonTextStyle,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    marginBottom: moderateScale(3),
    marginHorizontal: moderateScale(2),
    // padding: moderateScale(15),
    paddingRight: moderateScale(15),
    // paddingVertical: moderateScale(10),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
    position: 'relative',
    overflow: 'hidden',
  },
  selectedItemCard: {
    ...commonTextStyle,
    borderColor: '#0D326F',
    borderWidth: 2,
    backgroundColor: '#f8f9fa',
    shadowColor: '#0D326F',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  cardContent: {
    ...commonTextStyle,
    flexDirection: 'column',
    width: '100%',
  },
  productInfoContainer: {
    ...commonTextStyle,
    height: hp(5),
    justifyContent: 'center',
  },
  selectedItemRowContainer: {
    ...commonTextStyle,
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(2),
    paddingRight: moderateScale(6),
    paddingLeft: moderateScale(2),
    marginTop: moderateScale(0),
  },
  nameWithFavoriteContainer: {
    ...commonTextStyle,
    flexDirection: 'row',
    alignItems: 'center',
    width: '60%',
  },
  selectItemName: {
    ...commonTextStyle,
    flex: 1,
    fontSize: RFValue(15),
    color: '#1e293b',
    letterSpacing: -0.3,
    // marginLeft: moderateScale(4),
  },
  favoriteButton: {
    padding: moderateScale(2),
  },
  favoriteButtonText: {
    fontSize: moderateScale(18),
    color: '#f59e0b',
  },
  price_unit_Text: {
    ...commonTextStyle,
    width: '25%',
    fontSize: RFValue(14),
    textAlign: 'left',
  },
  orderButton: {
    ...commonTextStyle,
    width: wp(15),
    height: hp(4),
    backgroundColor: '#fff',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#0D326F',
    borderWidth: 1.5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  orderButtonText: {
    ...commonTextStyle,
    color: '#0D326F',
    fontSize: RFValue(13),
  },
  additionalRowContainer: {
    // 추가 스타일이 필요하면 여기에 작성
  },
  priceText: {
    ...commonTextStyle,
    fontSize: RFValue(12),
    color: '#0D326F',
    position: 'relative',
    width: wp(35),
    // left: wp(1.2),
    textAlign: 'left',
  },
  unitText: {
    ...commonTextStyle,
    fontSize: RFValue(12),
    color: '#555555',
    textAlign: 'left',
    position: 'relative',
    width: wp(30),
    // left: wp(1.2),
  },
  quantityControlContainer: {
    ...commonTextStyle,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: moderateScale(25),
    overflow: 'hidden',
    marginRight: moderateScale(8),
    backgroundColor: '#f8fafc',
    marginBottom: moderateScale(10),
  },
  quantityButton: {
    ...commonTextStyle,
    width: wp(12),
    height: hp(5),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  quantityText: {
    ...commonTextStyle,
    fontSize: RFValue(15),
    fontWeight: '600',
    color: '#0D326F',
    textAlign: 'center',
    minWidth: wp(15),
    maxWidth: wp(20),
    height: hp(5),
    backgroundColor: '#fff',
  },
  disabledButton: {
    ...commonTextStyle,
    opacity: 0.3,
  },
  errorContainer: {
    ...commonTextStyle,
    marginTop: moderateScale(2),
    backgroundColor: '#fee2e2',
    borderRadius: moderateScale(8),
    padding: moderateScale(8),
    marginLeft: moderateScale(8),
    marginBottom: moderateScale(2),
    width: '100%',
  },
  errorText: {
    ...commonTextStyle,
    color: '#dc2626',
    fontSize: RFValue(12),
    textAlign: 'center',
  },
  loading_Container: {
    ...commonTextStyle,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  loading_Text: {
    marginTop: moderateScale(3),
    fontSize: RFValue(16),
    fontWeight: '600',
    left: 5,
    color: '#00000080',
    alignItems: 'center',
    ...commonTextStyle,
  },
  container: {
    ...commonTextStyle,
    flex: 1,
    padding: moderateScale(20),
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  scrollContainer: {
    ...commonTextStyle,
    flexGrow: 1,
    backgroundColor: '#fff',
    paddingHorizontal: moderateScale(16),
  },
  fixedHeaderContainer: {
    ...commonTextStyle,
    backgroundColor: '#fff',
    paddingTop: moderateScale(10),
    // paddingBottom: moderateScale(5),
    zIndex: 10,
    shadowColor: '#000',
    width: '100%'
  },
  categorySection: {
    ...commonTextStyle,
    backgroundColor: '#ffffff',
    paddingVertical: moderateScale(15),
    marginBottom: moderateScale(15),
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  sectionTitle: {
    ...commonTextStyle,
    fontSize: RFValue(18),
    fontWeight: '700',
    color: '#0D326F',
    marginBottom: moderateScale(3),
    paddingHorizontal: moderateScale(16),
    width: '100%',
    borderLeftWidth: 4,
    borderLeftColor: '#0D326F',
    paddingLeft: moderateScale(10),
    marginLeft: moderateScale(5),
  },
  categoryList: {
    ...commonTextStyle,
    flexDirection: 'row',
    marginTop: moderateScale(10),
    paddingRight: moderateScale(16),
  },
  categoryButton: {
    ...commonTextStyle,
    marginHorizontal: scale(4),
    paddingHorizontal: moderateScale(15),
    paddingVertical: verticalScale(8),
    borderRadius: moderateScale(20),
    backgroundColor: 'white',
    borderColor: '#e2e8f0',
    borderWidth: scale(1),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  categoryButtonActive: {
    ...commonTextStyle,
    backgroundColor: '#0D326F',
    borderColor: '#0D326F',
  },
  categoryButtonText: {
    ...commonTextStyle,
    fontSize: RFValue(14),
    fontWeight: '600',
    color: '#64748b',
  },
  categoryButtonTextActive: {
    color: '#ffffff',
  },
  sectionContainer: {
    ...commonTextStyle,
    backgroundColor: '#fff',
  },
  sectionTitle_2: {
    ...commonTextStyle,
    fontSize: RFValue(18),
    fontWeight: '700',
    color: '#0D326F',
    marginBottom: moderateScale(5),
    paddingHorizontal: moderateScale(16),
    width: '70%',
    borderLeftWidth: 4,
    borderLeftColor: '#0D326F',
    paddingLeft: moderateScale(10),
    marginLeft: moderateScale(5),
  },
  headerContainer: {
    ...commonTextStyle,
    backgroundColor: '#f8f9fa',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: moderateScale(12),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(12),
    marginTop: moderateScale(8),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  item_headerText: {
    ...commonTextStyle,
    width: '60%',
    fontSize: RFValue(15),
    fontWeight: '700',
    color: '#0D326F',
    textAlign: 'left',
    letterSpacing: -0.3,
  },
  price_headerText: {
    ...commonTextStyle,
    width: '25%',
    fontSize: RFValue(15),
    fontWeight: '700',
    color: '#0D326F',
    textAlign: 'left',
    paddingRight: moderateScale(10),
  },
  listContainer: {
    ...commonTextStyle,
    marginTop: moderateScale(5),
    marginBottom: moderateScale(0),
  },
  footerContainer: {
    ...commonTextStyle,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    backgroundColor: '#fff',
    paddingHorizontal: moderateScale(16),
    // paddingVertical: moderateScale(12),
    height: '9%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -3,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 5,
  },
  footerPriceText: {
    ...commonTextStyle,
    color: '#0D326F',
    fontSize: RFValue(17),
    fontWeight: '700',
  },
  footerButton: {
    ...commonTextStyle,
    backgroundColor: '#0D326F',
    borderRadius: 25,
    paddingHorizontal: wp(6),
    paddingVertical: hp(1.5),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  footerButtonDisabled: {
    ...commonTextStyle,
    backgroundColor: '#94a3b8',
  },
  footerButtonText: {
    ...commonTextStyle,
    color: '#fff',
    fontSize: RFValue(13),
  },
  confirm_selectedItemsSection: {
    ...commonTextStyle,
    paddingVertical: moderateScale(20),
    paddingHorizontal: moderateScale(16),
    backgroundColor: '#ffffff',
  },
  confirm_sectionTitle: {
    ...commonTextStyle,
    fontSize: RFValue(22),
    fontWeight: '700',
    color: '#0D326F',
    // marginBottom: moderateScale(5),
    width: '100%',
    textAlign: 'center',
    borderBottomWidth: 2,
    borderBottomColor: '#e2e8f0',
    paddingBottom: moderateScale(5),
  },
  confirmationItemRow: {
    ...commonTextStyle,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: moderateScale(6),
    paddingHorizontal: moderateScale(10),
    borderBottomWidth: 1,
    borderColor: '#e2e8f0',
    width: '100%',
    height: '20%',
    backgroundColor: '#ffffff',
    // borderRadius: moderateScale(8),
    // marginBottom: moderateScale(8),
  },
  confirm_selectItemName: {
    ...commonTextStyle,
    flex: 3,
    fontSize: RFValue(16),
    // fontWeight: '600',
    color: '#1e293b',
    // marginBottom: moderateScale(4),
    width: '100%',
  },
  confirm_unitText: {
    ...commonTextStyle,
    flex: 0.7,
    fontSize: RFValue(15),
    color: '#0D326F',
  },
  confirm_priceText: {
    ...commonTextStyle,
    fontSize: RFValue(16),
  },
  totalRow: {
    ...commonTextStyle,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: moderateScale(15),
    borderTopWidth: 1,
    borderColor: '#e2e8f0',
  },
  totalText: {
    ...commonTextStyle,
    color: '#0D326F',
    fontSize: RFValue(17),
    fontWeight: '700',
  },
  order_request_Button: {
    ...commonTextStyle,
    backgroundColor: '#0D326F',
    paddingVertical: moderateScale(12),
    paddingHorizontal: moderateScale(20),
    borderRadius: 25,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  order_request_ButtonText: {
    ...commonTextStyle,
    color: 'white',
    fontSize: RFValue(16),
    fontWeight: 'bold',
  },
  selectItemRowContainer: {
    ...commonTextStyle,
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(2),
    paddingRight: moderateScale(6),
    paddingLeft: moderateScale(2),
  },
  cancelButton: {
    borderColor: '#ef4444',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    ...commonTextStyle,
    color: '#ef4444',
    fontSize: RFValue(13),
  },
  productCardContent: {
    ...commonTextStyle,
    flexDirection: 'column',
    width: '100%',
  },
  productCardRow: {
    ...commonTextStyle,
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(2),
    paddingRight: moderateScale(6),
    paddingLeft: moderateScale(2),
  },
  productName: {
    ...commonTextStyle,
    flex: 1,
    fontSize: RFValue(15),
    color: '#1e293b',
    letterSpacing: -0.3,
    // marginLeft: moderateScale(4),
  },
  productPrice: {
    ...commonTextStyle,
    width: '25%',
    fontSize: RFValue(14),
    textAlign: 'left',
  },
  
  addButton: {
    ...commonTextStyle,
    backgroundColor: '#0D326F',
    paddingVertical: moderateScale(6),
    paddingHorizontal: moderateScale(10),
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    ...commonTextStyle,
    color: '#fff',
    fontSize: RFValue(12),
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    // marginBottom: moderateScale(5),
    // marginHorizontal: moderateScale(16),
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: moderateScale(8),
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    overflow: 'hidden',
  },
  searchInput: {
    ...commonTextStyle,
    flex: 1,
    paddingVertical: moderateScale(10),
    paddingHorizontal: moderateScale(12),
    fontSize: RFValue(14),
    color: '#1e293b',
  },
  searchIcon: {
    padding: moderateScale(10),
  },
  searchIconSize: {
    width: RFValue(20),
    height: RFValue(20),
  },
  searchIconContainer: {
    marginRight: moderateScale(8),
    borderRadius: moderateScale(20),
  },
});
