import { StyleSheet, Dimensions, TextStyle } from "react-native";
import { moderateScale, scale, verticalScale } from "react-native-size-matters";
import { RFValue } from "react-native-responsive-fontsize";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

const { height: screenHeight } = Dimensions.get("window");

const commonTextStyle = (customStyle: Partial<TextStyle> = {}): TextStyle => ({
  fontFamily: "PretendardVariable",
  fontWeight: customStyle.fontWeight ? customStyle.fontWeight : "400",
  ...customStyle,
});

export const inventoryStyles = StyleSheet.create({
  container: {
    ...commonTextStyle,
    flex: 1,
    padding: moderateScale(20),
    backgroundColor: "#fff",
  },
  term_of_name: {
    ...commonTextStyle,
    fontSize: RFValue(16),
    fontWeight: "bold",
    marginBottom: moderateScale(10),
    color: "#0D326F",
  },
  title: {
    ...commonTextStyle,
    fontSize: RFValue(18),
    fontWeight: "700",
    color: "#0D326F",
    marginBottom: moderateScale(12),
    // paddingHorizontal: moderateScale(16),
    width: "65%",
    borderLeftWidth: 4,
    borderLeftColor: "#0D326F",
    paddingLeft: moderateScale(5),
    marginLeft: moderateScale(5),
  },
  inventory_HeaderContainer: {
    ...commonTextStyle,
    backgroundColor: "#f8f9fa",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    // borderRadius: moderateScale(12),
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(12),
    // marginBottom: moderateScale(10),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  inventory_item_headerText: {
    ...commonTextStyle,
    width: "65%",
    fontSize: RFValue(15),
    fontWeight: "700",
    color: "#0A2A5E",
    textAlign: "left",
  },
  inventory_unit_headerText: {
    ...commonTextStyle,
    width: "35%",
    fontSize: RFValue(15),
    fontWeight: "700",
    color: "#0A2A5E",
    textAlign: "center",
    marginLeft: moderateScale(5),
  },
  itemContainer: {
    ...commonTextStyle,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: "#e2e8f0",
    // borderRadius: moderateScale(10),
    // marginBottom: moderateScale(2),
    padding: moderateScale(15),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
  },
  name_itemText: {
    ...commonTextStyle,
    width: "65%",
    fontSize: RFValue(15),
    fontWeight: "500",
    color: "#1e293b",
    letterSpacing: -0.3,
  },
  unit_itemText: {
    ...commonTextStyle,
    width: "20%",
    fontSize: RFValue(13),
    fontWeight: "600",
    color: "#0A2A5E",
    textAlign: "center",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: moderateScale(8),
    paddingVertical: moderateScale(4),
    // paddingHorizontal: moderateScale(4),
    backgroundColor: "#f8fafc",
  },
  inventory_selectItemRowContainer: {
    ...commonTextStyle,
    flexDirection: "row",
    alignItems: "center",
    paddingRight: moderateScale(6),
    paddingLeft: moderateScale(2),
    gap: moderateScale(30),
    position: "relative",
  },
  flat_inventory: {
    ...commonTextStyle,
    flex: 1,
    marginBottom: moderateScale(2),
  },
  editButton: {
    ...commonTextStyle,
    backgroundColor: "#0D326F",
    borderRadius: 25,
    paddingVertical: moderateScale(12),
    paddingHorizontal: moderateScale(30),
    marginTop: moderateScale(10),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  editButtonText: {
    ...commonTextStyle,
    color: "#ffffff",
    fontSize: RFValue(16),
    fontWeight: "bold",
    textAlign: "center",
  },
  message: {
    ...commonTextStyle,
    fontSize: RFValue(16),
    color: "#555",
    textAlign: "center",
    marginTop: 20,
  },
  status_container: {
    ...commonTextStyle,
    flex: 1,
    alignItems: "stretch",
    justifyContent: "flex-start",
    backgroundColor: "#fff",
    paddingHorizontal: moderateScale(16),
  },
  inventory_cardContent: {
    ...commonTextStyle,
    flexDirection: "column",
    width: "100%",
    // height: hp(3)
  },
});
export const toggleButtonStyles = StyleSheet.create({
  container: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: moderateScale(10),
    gap: moderateScale(1),
  },
  headerContainer: {
    backgroundColor: "#f8fafc",
    borderRadius: moderateScale(10),
    padding: moderateScale(8),
    marginHorizontal: moderateScale(10),
    marginBottom: moderateScale(10),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  button: {
    flex: 1,
    paddingVertical: moderateScale(8),
    paddingHorizontal: moderateScale(16),
    borderRadius: moderateScale(6),
    borderWidth: 1,
    borderBottomWidth: 0.3,
    borderColor: "#e0e0e0",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 0,
  },
  buttonActive: {
    backgroundColor: "#0A2A5E",
    borderWidth: 0,
    borderColor: "transparent",
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 0,
  },
  buttonText: {
    fontSize: 14,
    color: "#0A2A5E",
    fontWeight: "bold",
  },
  buttonTextActive: {
    color: "#fff",
  },
});

export const headerRowStyles = StyleSheet.create({
  container: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginVertical: moderateScale(4),
  },
  rightContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  buttonContainer: {
    flexDirection: "row",
    gap: moderateScale(10),
  },
  smallButton: {
    backgroundColor: "#f8fafc",
    paddingHorizontal: moderateScale(10),
    paddingVertical: verticalScale(5),
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: "#0D326F",
    shadowColor: "#0D326F",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 2,
    justifyContent: "center",
    alignItems: "center",
  },
  activeButton: {
    backgroundColor: "#0D326F",
    paddingHorizontal: moderateScale(10),
    paddingVertical: verticalScale(5),
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: "#0D326F",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonText: {
    ...commonTextStyle,
    color: "#0D326F",
    fontSize: RFValue(11),
    fontWeight: "500",
  },
  activeButtonText: {
    ...commonTextStyle,
    color: "#FFFFFF",
    fontSize: RFValue(11),
    fontWeight: "600",
  },
  disabledButton: {
    backgroundColor: "#0D326F",
    paddingHorizontal: moderateScale(10),
    paddingVertical: verticalScale(5),
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: "#cccccc",
    shadowColor: "#999999",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 1,
    justifyContent: "center",
    alignItems: "center",
    opacity: 0.7,
  },
  disabledButtonText: {
    ...commonTextStyle,
    color: "#ffffff",
    fontSize: RFValue(11),
    fontWeight: "400",
  },
});

export const modalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: "80%",
    backgroundColor: "#fff",
    padding: moderateScale(20),
    borderRadius: moderateScale(10),
    alignItems: "center",
  },
  modalText: {
    marginBottom: moderateScale(20),
    fontSize: 16,
    textAlign: "center",
  },
  errorModalContainer: {
    width: "85%",
    backgroundColor: "#fff",
    padding: moderateScale(25),
    borderRadius: moderateScale(12),
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    borderWidth: 3,
    borderColor: "#0D326F",
  },
  errorTitle: {
    fontSize: RFValue(22),
    fontWeight: "700",
    color: "#e53e3e",
    marginBottom: moderateScale(15),
    width: "100%",
    textAlign: "center",
    borderBottomWidth: 2,
    borderBottomColor: "#e2e8f0",
    paddingBottom: moderateScale(10),
  },
  errorText: {
    fontSize: RFValue(17),
    color: "#1e293b",
    marginBottom: moderateScale(20),
    textAlign: "left",
    lineHeight: moderateScale(26),
    fontWeight: "500",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    marginTop: moderateScale(10),
  },
  confirmButton: {
    backgroundColor: "#0D326F",
    paddingVertical: moderateScale(10),
    paddingHorizontal: moderateScale(20),
    borderRadius: moderateScale(8),
    marginHorizontal: moderateScale(5),
    minWidth: "40%",
    alignItems: "center",
  },
  cancelButton: {
    backgroundColor: "#e2e8f0",
    paddingVertical: moderateScale(10),
    paddingHorizontal: moderateScale(20),
    borderRadius: moderateScale(8),
    marginHorizontal: moderateScale(5),
    minWidth: "40%",
    alignItems: "center",
  },
  buttonText: {
    fontSize: RFValue(14),
    fontWeight: "600",
    color: "#ffffff",
  },
  cancelButtonText: {
    fontSize: RFValue(14),
    fontWeight: "600",
    color: "#1e293b",
  },
});

export const searchStyles = StyleSheet.create({
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: moderateScale(5),
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: moderateScale(8),
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    overflow: "hidden",
  },
  searchInput: {
    flex: 1,
    paddingVertical: moderateScale(10),
    paddingHorizontal: moderateScale(12),
    fontSize: 14,
    color: "#1e293b",
  },
  searchIcon: {
    padding: moderateScale(10),
  },
  searchIconSize: {
    width: 20,
    height: 20,
  },
  searchIconContainer: {
    marginRight: moderateScale(8),
    borderRadius: moderateScale(20),
  },
});

export const editModeStyles = StyleSheet.create({
  controlContainer: {
    width: "20%",
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  inputContainer: {
    width: "100%",
    position: "relative",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  controlButtonsGroup: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    position: "relative",
  },
  controlButtonsContainer: {
    flexDirection: "row",
    alignItems: "center",
    position: "absolute",
    right: 0,
  },
  controlButton: {
    padding: moderateScale(4),
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: moderateScale(6),
    backgroundColor: "#f8fafc",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 1,
    width: moderateScale(30),
    height: moderateScale(30),
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  deleteButton: {
    padding: moderateScale(6),
    borderWidth: 1,
    borderColor: "#ffcccc",
    borderRadius: moderateScale(8),
    marginLeft: moderateScale(4),
    backgroundColor: "#fff5f5",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 1,
  },
  quantityInput: {
    ...commonTextStyle,
    width: "100%",
    textAlign: "center",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: moderateScale(8),
    paddingVertical: moderateScale(4),
    paddingHorizontal: moderateScale(4),
    backgroundColor: "#f8fafc",
    fontSize: RFValue(13),
    fontWeight: "600",
    color: "#0A2A5E",
    minWidth: moderateScale(40),
  },
  leftButton: {
    position: "absolute",
    left: moderateScale(-32),
    zIndex: 2,
  },
  rightButton: {
    position: "absolute",
    right: moderateScale(-32),
    zIndex: 2,
  },
});

export const OrderRequeststyle = StyleSheet.create({
  selectItemCard: {
    ...commonTextStyle,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    marginBottom: moderateScale(3),
    marginHorizontal: moderateScale(2),
    paddingRight: moderateScale(15),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
    position: "relative",
    overflow: "hidden",
  },
  selectedItemCard: {
    ...commonTextStyle,
    borderColor: "#0D326F",
    borderWidth: 2,
    backgroundColor: "#f8f9fa",
    shadowColor: "#0D326F",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  cardContent: {
    ...commonTextStyle,
    flexDirection: "column",
    width: "100%",
  },
  productInfoContainer: {
    ...commonTextStyle,
    height: hp(5),
    justifyContent: "center",
  },
  selectedItemRowContainer: {
    ...commonTextStyle,
    flexDirection: "row",
    alignItems: "center",
    gap: moderateScale(2),
    paddingRight: moderateScale(6),
    paddingLeft: moderateScale(2),
    marginTop: moderateScale(5),
  },
  nameWithFavoriteContainer: {
    ...commonTextStyle,
    flexDirection: "row",
    alignItems: "center",
    width: "60%",
  },
  selectItemName: {
    ...commonTextStyle,
    flex: 1,
    fontSize: RFValue(15),
    color: "#1e293b",
    letterSpacing: -0.3,
  },
  favoriteButton: {
    padding: moderateScale(2),
  },
  favoriteButtonText: {
    fontSize: moderateScale(18),
    color: "#f59e0b",
  },
  price_unit_Text: {
    ...commonTextStyle,
    width: "25%",
    fontSize: RFValue(14),
    textAlign: "left",
  },
  orderButton: {
    ...commonTextStyle,
    width: wp(15),
    height: hp(4),
    backgroundColor: "#fff",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#0D326F",
    borderWidth: 1.5,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  orderButtonText: {
    ...commonTextStyle,
    color: "#0D326F",
    fontSize: RFValue(13),
  },
  additionalRowContainer: {
    height: hp(7),
  },
  priceText: {
    ...commonTextStyle,
    fontSize: RFValue(12),
    color: "#0D326F",
    position: "relative",
    width: wp(35),
    textAlign: "left",
  },
  unitText: {
    ...commonTextStyle,
    fontSize: RFValue(12),
    color: "#555555",
    textAlign: "left",
    position: "relative",
    width: wp(30),
  },
  quantityControlContainer: {
    ...commonTextStyle,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#e2e8f0",
    borderRadius: moderateScale(25),
    overflow: "hidden",
    marginRight: moderateScale(8),
    backgroundColor: "#f8fafc",
    marginBottom: moderateScale(10),
  },
  quantityButton: {
    ...commonTextStyle,
    width: wp(12),
    height: hp(5),
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  quantityText: {
    ...commonTextStyle,
    fontSize: RFValue(15),
    fontWeight: "600",
    color: "#0D326F",
    textAlign: "center",
    minWidth: wp(15),
    maxWidth: wp(20),
    height: hp(5),
    backgroundColor: "#fff",
  },
  disabledButton: {
    ...commonTextStyle,
    opacity: 0.3,
  },
  errorContainer: {
    ...commonTextStyle,
    backgroundColor: "#fee2e2",
    borderRadius: moderateScale(8),
    padding: moderateScale(8),
    marginLeft: moderateScale(8),
    marginBottom: moderateScale(4),
    width: "100%",
  },
  errorText: {
    ...commonTextStyle,
    color: "#dc2626",
    fontSize: RFValue(12),
    textAlign: "center",
  },
  loading_Container: {
    ...commonTextStyle,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  loading_Text: {
    marginTop: moderateScale(3),
    fontSize: RFValue(16),
    fontWeight: "600",
    left: 5,
    color: "#00000080",
    alignItems: "center",
    ...commonTextStyle,
  },
  container: {
    ...commonTextStyle,
    flex: 1,
    padding: moderateScale(20),
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  scrollContainer: {
    ...commonTextStyle,
    flexGrow: 1,
    backgroundColor: "#fff",
    paddingHorizontal: moderateScale(16),
  },
  fixedHeaderContainer: {
    ...commonTextStyle,
    backgroundColor: "#fff",
    paddingTop: moderateScale(10),
    zIndex: 10,
    shadowColor: "#000",
    width: "100%",
  },
  categorySection: {
    ...commonTextStyle,
    backgroundColor: "#ffffff",
    paddingVertical: moderateScale(15),
    marginBottom: moderateScale(15),
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  sectionTitle: {
    ...commonTextStyle,
    fontSize: RFValue(18),
    fontWeight: "600",
    color: "#0D326F",
    marginBottom: moderateScale(3),
    paddingHorizontal: moderateScale(16),
    width: "100%",
    borderLeftWidth: 4,
    borderLeftColor: "#0D326F",
    paddingLeft: moderateScale(10),
    marginLeft: moderateScale(5),
  },
  categoryList: {
    ...commonTextStyle,
    flexDirection: "row",
    marginTop: moderateScale(10),
    paddingRight: moderateScale(16),
  },
  categoryButton: {
    ...commonTextStyle,
    marginHorizontal: scale(4),
    paddingHorizontal: moderateScale(15),
    paddingVertical: verticalScale(8),
    borderRadius: moderateScale(20),
    backgroundColor: "white",
    borderColor: "#e2e8f0",
    borderWidth: scale(1),
    alignItems: "center",
    justifyContent: "center",
  },
  categoryButtonActive: {
    ...commonTextStyle,
    backgroundColor: "#0D326F",
    borderColor: "#0D326F",
  },
  categoryButtonText: {
    ...commonTextStyle,
    fontSize: RFValue(14),
    fontWeight: "600",
    color: "#64748b",
  },
  categoryButtonTextActive: {
    color: "#ffffff",
  },
  sectionContainer: {
    ...commonTextStyle,
    backgroundColor: "#fff",
  },
  sectionTitle_2: {
    ...commonTextStyle,
    fontSize: RFValue(18),
    fontWeight: "600",
    color: "#0D326F",
    marginBottom: moderateScale(5),
    paddingHorizontal: moderateScale(16),
    width: "70%",
    borderLeftWidth: 4,
    borderLeftColor: "#0D326F",
    paddingLeft: moderateScale(10),
    marginLeft: moderateScale(5),
  },
  headerContainer: {
    ...commonTextStyle,
    backgroundColor: "#f8f9fa",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: moderateScale(12),
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(12),
    marginTop: moderateScale(8),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  item_headerText: {
    ...commonTextStyle,
    width: "60%",
    fontSize: RFValue(15),
    fontWeight: "700",
    color: "#0D326F",
    textAlign: "left",
    letterSpacing: -0.3,
  },
  price_headerText: {
    ...commonTextStyle,
    width: "25%",
    fontSize: RFValue(15),
    fontWeight: "700",
    color: "#0D326F",
    textAlign: "left",
    paddingRight: moderateScale(10),
  },
  listContainer: {
    ...commonTextStyle,
    marginTop: moderateScale(5),
    marginBottom: moderateScale(0),
  },
  footerContainer: {
    ...commonTextStyle,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    backgroundColor: "#fff",
    paddingHorizontal: moderateScale(16),
    height: "9%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: -3,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 5,
  },
  footerPriceText: {
    ...commonTextStyle,
    color: "#0D326F",
    fontSize: RFValue(17),
    fontWeight: "700",
  },
  footerButton: {
    ...commonTextStyle,
    backgroundColor: "#0D326F",
    borderRadius: 25,
    paddingHorizontal: wp(6),
    paddingVertical: hp(1.5),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  footerButtonDisabled: {
    ...commonTextStyle,
    backgroundColor: "#94a3b8",
  },
  footerButtonText: {
    ...commonTextStyle,
    color: "#fff",
    fontSize: RFValue(13),
  },
  confirm_selectedItemsSection: {
    ...commonTextStyle,
    paddingVertical: moderateScale(20),
    paddingHorizontal: moderateScale(16),
    backgroundColor: "#ffffff",
  },
  confirm_sectionTitle: {
    ...commonTextStyle,
    fontSize: RFValue(22),
    fontWeight: "700",
    color: "#0D326F",
    width: "100%",
    textAlign: "center",
    borderBottomWidth: 2,
    borderBottomColor: "#e2e8f0",
    paddingBottom: moderateScale(5),
  },
  confirmationItemRow: {
    ...commonTextStyle,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: moderateScale(6),
    paddingHorizontal: moderateScale(10),
    borderBottomWidth: 1,
    borderColor: "#e2e8f0",
    width: "100%",
    height: hp(5),
    backgroundColor: "#ffffff",
  },
  confirm_selectItemName: {
    ...commonTextStyle,
    flex: 3,
    fontSize: RFValue(16),
    color: "#1e293b",
    width: "100%",
  },
  confirm_unitText: {
    ...commonTextStyle,
    flex: 0.7,
    fontSize: RFValue(15),
    color: "#0D326F",
  },
  confirm_priceText: {
    ...commonTextStyle,
    fontSize: RFValue(16),
  },
  totalRow: {
    ...commonTextStyle,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: moderateScale(15),
    borderTopWidth: 1,
    borderColor: "#e2e8f0",
  },
  totalText: {
    ...commonTextStyle,
    color: "#0D326F",
    fontSize: RFValue(17),
    fontWeight: "700",
  },
  order_request_Button: {
    ...commonTextStyle,
    backgroundColor: "#0D326F",
    paddingVertical: moderateScale(12),
    paddingHorizontal: moderateScale(20),
    borderRadius: 25,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  order_request_ButtonText: {
    ...commonTextStyle,
    color: "white",
    fontSize: RFValue(16),
    fontWeight: "bold",
  },
  selectItemRowContainer: {
    ...commonTextStyle,
    flexDirection: "row",
    alignItems: "center",
    gap: moderateScale(2),
    paddingRight: moderateScale(6),
    paddingLeft: moderateScale(2),
  },
  cancelButton: {
    borderColor: "#ef4444",
    alignItems: "center",
    justifyContent: "center",
  },
  cancelButtonText: {
    ...commonTextStyle,
    color: "#ef4444",
    fontSize: RFValue(13),
  },
  productCardContent: {
    ...commonTextStyle,
    flexDirection: "column",
    width: "100%",
  },
  productCardRow: {
    ...commonTextStyle,
    flexDirection: "row",
    alignItems: "center",
    gap: moderateScale(2),
    paddingRight: moderateScale(6),
    paddingLeft: moderateScale(2),
    marginTop: moderateScale(5),
  },
  productName: {
    ...commonTextStyle,
    flex: 1,
    fontSize: RFValue(15),
    color: "#1e293b",
    letterSpacing: -0.3,
  },
  productPrice: {
    ...commonTextStyle,
    width: "25%",
    fontSize: RFValue(14),
    textAlign: "left",
  },
  addButton: {
    ...commonTextStyle,
    backgroundColor: "#0D326F",
    paddingVertical: moderateScale(6),
    paddingHorizontal: moderateScale(10),
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  addButtonText: {
    ...commonTextStyle,
    color: "#fff",
    fontSize: RFValue(12),
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: moderateScale(8),
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    overflow: "hidden",
  },
  searchInput: {
    ...commonTextStyle,
    flex: 1,
    paddingVertical: moderateScale(10),
    paddingHorizontal: moderateScale(12),
    fontSize: RFValue(14),
    color: "#1e293b",
  },
  searchIcon: {
    padding: moderateScale(10),
  },
  searchIconSize: {
    width: RFValue(20),
    height: RFValue(20),
  },
  searchIconContainer: {
    marginRight: moderateScale(8),
    borderRadius: moderateScale(20),
  },
});
