# Generated by Django 5.1.5 on 2025-02-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("기간", models.CharField(max_length=10)),
                ("매장_재고량", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "매장",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.store"
                    ),
                ),
                (
                    "품목",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="suppliers.item"
                    ),
                ),
            ],
            options={
                "unique_together": {("매장", "품목", "기간")},
            },
        ),
        migrations.CreateModel(
            name="WarehouseInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("기간", models.CharField(max_length=10)),
                ("창고_재고량", models.IntegerField()),
                (
                    "매장",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.store"
                    ),
                ),
                (
                    "품목",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="suppliers.item"
                    ),
                ),
            ],
            options={
                "unique_together": {("매장", "품목", "기간")},
            },
        ),
    ]
