# Generated by Django 5.1.5 on 2025-02-23 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("inventory", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="storeinventory",
            unique_together={("매장_id", "품목_id", "기간")},
        ),
        migrations.AlterUniqueTogether(
            name="warehouseinventory",
            unique_together={("매장_id", "품목_id", "기간")},
        ),
        migrations.CreateModel(
            name="StoreMonthEndInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("기간", models.CharField(max_length=7)),
                ("월말_재고량", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "매장_id",
                    models.ForeignKey(
                        db_column="매장_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.store",
                    ),
                ),
                (
                    "품목_id",
                    models.ForeignKey(
                        db_column="품목_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="suppliers.item",
                    ),
                ),
            ],
            options={
                "db_table": "매장_월말재고",
                "unique_together": {("매장_id", "품목_id", "기간")},
            },
        ),
    ]
