# Generated by Django 5.1.5 on 2025-03-21 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_storeinventory_unique_together_and_more"),
        ("suppliers", "0002_alter_item_입고단가"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseExpiration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("유통기한", models.CharField(max_length=10)),
                ("창고_재고량", models.IntegerField()),
                (
                    "품목_id",
                    models.ForeignKey(
                        db_column="품목_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="suppliers.item",
                    ),
                ),
            ],
            options={
                "db_table": "창고_유통기한",
                "unique_together": {("품목_id", "유통기한")},
            },
        ),
    ]
