# Generated by Django 5.1.5 on 2025-02-07 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("기간", models.CharField(max_length=7)),
                ("매출액", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "매장_id",
                    models.ForeignKey(
                        db_column="매장_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.store",
                    ),
                ),
            ],
            options={
                "db_table": "매출",
                "unique_together": {("매장_id", "기간")},
            },
        ),
    ]
