# Generated by Django 5.1.5 on 2025-02-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "협력사_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("협력사명", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "품목_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("품목명", models.CharField(max_length=255)),
                ("규격", models.CharField(blank=True, max_length=255, null=True)),
                ("단위", models.CharField(blank=True, max_length=50, null=True)),
                ("입고단가", models.DecimalField(decimal_places=2, max_digits=10)),
                ("입고단위", models.IntegerField(blank=True, null=True)),
                ("입고단위단가", models.IntegerField(blank=True, null=True)),
                (
                    "협력사",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suppliers.supplier",
                    ),
                ),
            ],
        ),
    ]
