# Generated by Django 5.1.5 on 2025-02-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="입고단가",
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
    ]
