# Generated by Django 5.1.5 on 2025-02-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="item",
            table="품목",
        ),
        migrations.AlterModelTable(
            name="supplier",
            table="협력사",
        ),
    ]
